---
- hosts: all
  vars_files:
    - vars/main.yaml
  pre_tasks:
  - name: create docroot
    file:
      path: "{{ apache_vhosts.documentroot }}"
      state: directory
      mode: 0755
      owner: www-data
      group: www-data
  roles:
  - { role: ansible-role-apache }
 